#Clone the repository, or download the theme of your choice:
# We use Alacritty's default Linux config directory as our storage location here.
#mkdir -p ~/.config/alacritty/themes
#git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
import = [
	"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[window]
decorations = "none"
opacity = 0.80
title = "Terminal"
blur = true
dynamic_title = false
decorations_theme_variant = "Dark"

[font]
normal = { family = "FiraCode Nerd Font", style = "Retina" }

