import = [
    "~/.config/alacritty/themes/themes/tokyonight_night.toml"
]

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
title = "Terminal"
dynamic_title = false
decorations_theme_variant = "Dark"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
style = "Bold"
